### PR TITLE
Getting the relevant pairs only

### PR DESCRIPTION
**Pull request by Omri93h**
from exchangeinfo API we take the pairs that status is trading.
before that we took every pair that ever traded in Binance

### CODE REVIEW

**Comment by b-fg** [comment]
Hi @Omri93h,

This looks great, thanks for the PR. I will run some tests soon and merge eventually.
Thanks for the contribution again.

Bernat

**Comment by b-fg** [comment]
I have added a small cleanup after your commits. Thanks!

**Comment by Omri93h** [comment]
Thank you too, i hope you will add more TA functions one day, really
looking into it, thanks!

‫בתאריך יום ו׳, 9 באוג׳ 2019 ב-20:52 מאת ‪Bernat Font Garcia‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Omri93h** [comment]
Hi Bernat,
i really want to know if your experiencing the same problem i suddenly have
with Nuatsbot or is it because of Binance API updates?
[image: image.png]



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

‫בתאריך שבת, 10 באוג׳ 2019 ב-8:10 מאת ‪Omri Haham‬‏ <‪omri93h@gmail.com‬‏>:‬

**Pull request merged**
